version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DB_DIALECT}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ignat
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_graphql
    ports:
      - '5432:5432'
